---
title: "Height Report"
output: 
  word_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      include = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      dpi = 150)
```

```{r}
# Let's load the tidyverse
library(tidyverse)

# Let's import our data
nhanes <- read_csv("data/nhanes.csv")
```


# Introduction

This is a report written about average height of people in the United States.

## Distribution of Height

The following chart shows the distribution of height.

```{r}
# YOUR CODE HERE

# Make a histogram that shows the distribution of height (hint: copy from the 04-data-visualization-exercises.Rmd file).
```

## Height by Gender

The following chart shows the distribution of height, broken down by gender.

```{r}
# YOUR CODE HERE

# Copy your histogram from above and add a facet_wrap line to make two charts, one for females and one for males.
```

## Height by Age

```{r}
# YOUR CODE HERE

# Make a table that shows height by age, using the age_decade variable to group_by before summarizing
```




